function feedback() {
  var el_div0 = $("<div />", { class: "row" })
  var el_div1 = $("<div />", { class: "row" })
  var el_button0 = $("<button />", { id: "fb-send", class: "btn btn-success", text: "Send" })
  var el_div0_label0 = $("<label />", { text: "E-mail" })
  var el_div1_label0 = $("<label />", { text: "Comment" })
  var el_div0_div0 = $("<div />")
  var el_div1_div0 = $("<div />")
  var el_div0_div0_input0 = $("<input />", { id: "fb-email" })
  var el_div1_div0_textarea0 = $("<textarea />", { id: "fb-text" })
  el_div1_div0.append(el_div1_div0_textarea0)
  el_div0_div0.append(el_div0_div0_input0)
  el_div0.append(el_div0_label0)
  el_div1.append(el_div1_label0)
  el_div0.append(el_div0_div0)
  el_div1.append(el_div1_div0)
  $("form").append(el_div0)
  $("form").append(el_div1)
  $("form").append(el_button0)
  $("form").css("text-align", "center")
  $("form > button").css("width", "100px")
  $("form > div").addClass("form-group row")
  $("form > div > label").addClass("col-form-label col-form-label-sm text-right mr-2")
  $("form > div > label").css("width", "60px")
  $("form > div > div").addClass("flex-fill mr-1")
  $("form > div > div > input").addClass("form-control form-control-sm")
  $("form > div > div > input").attr("type", "email")
  $("form > div > div > textarea").addClass("form-control form-control-sm")
  $("form > div > div > textarea").attr("rows", 5)
  document.getElementById("fb-send").addEventListener("click", function (e) {
    e.preventDefault()
    let request = new XMLHttpRequest()
    request.open("POST", "/mongodb/api/feedback/recent", true)
    request.setRequestHeader("Content-Type", "application/json; charset=UTF-8")
    let json = { email: document.getElementById("fb-email").value, text: document.getElementById("fb-text").value }
    request.send(JSON.stringify(json))
    alert("Your message is sent")
  })
  document.getElementById("fb-send").setAttribute("data-dismiss", "modal")
}